# .github/workflows/deploy.yml
name: Build and Deploy Angular SSG to Firebase

on:
  push:
    branches: [main]
  repository_dispatch: # permet à Directus de déclencher un rebuild
    types: [content_update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Install dependencies
        run: npm install

      - name: Generate static site
        run: npm run prerender --if-present

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
